### ISSUE TITLE
unnecessary empty tag

### ISSUE THREAD

**Issue by aminmahrami** [AllouhM/-hyf-html-css-#2]
https://github.com/AllouhM/-hyf-html-css-/blob/7331456616c11646a8f80a2d4f1d351678bb515e/week1/index.html#L39

**Comment by aminmahrami** [comment]
https://github.com/AllouhM/-hyf-html-css-/blob/7331456616c11646a8f80a2d4f1d351678bb515e/week1/index.html#L52 here there is no need for extra empty line

**Comment by aminmahrami** [comment]
https://github.com/AllouhM/-hyf-html-css-/blob/7331456616c11646a8f80a2d4f1d351678bb515e/week1/index.html#L106 
It's good that you know about article tag but it's not for here as it's not a article than a list so it's better to use `div` instead.

**Comment by AllouhM** [comment]
Thank you Amin
